/**
 * Azure AD SSO Authentication Module for thesun
 *
 * Enterprise-grade browser-based SSO authentication for Microsoft/Azure AD/Entra ID
 * protected services. This module enables generated MCPs to authenticate to enterprise
 * applications that use Azure AD, Entra ID, or Microsoft SSO.
 *
 * Features:
 * - Headless-first authentication (background, no visible browser)
 * - Automatic fallback to visible browser if headless fails
 * - Automatic 401 detection and re-authentication
 * - Credential storage in system keychain (secure)
 * - Cookie caching with expiration detection
 * - MFA/TOTP script support (optional)
 * - Multi-selector resilience for Azure AD form fields
 * - Proper browser cleanup and timeouts
 *
 * Based on the battle-tested ServiceNow MCP authentication system.
 */

import { z } from "zod";

// ============================================================================
// Configuration Schema
// ============================================================================

export const AzureAdSsoConfigSchema = z.object({
  toolName: z
    .string()
    .describe("Name of the tool/service (e.g., 'servicenow', 'sharepoint')"),
  loginUrl: z.string().url().describe("URL that triggers Azure AD login"),
  successUrlPatterns: z
    .array(z.string())
    .default([])
    .describe("URL patterns indicating successful auth (regex strings)"),
  headlessTimeout: z
    .number()
    .default(60000)
    .describe("Timeout for headless auth (ms)"),
  visibleTimeout: z
    .number()
    .default(300000)
    .describe("Timeout for visible browser auth (ms)"),
  cookieMaxAge: z
    .number()
    .default(8 * 60 * 60 * 1000)
    .describe("Cookie cache max age (ms)"),
  enableMfa: z
    .boolean()
    .default(false)
    .describe("Whether MFA/TOTP is expected"),
});

export type AzureAdSsoConfig = z.infer<typeof AzureAdSsoConfigSchema>;

// ============================================================================
// Code Generation - Azure AD Automator Module
// ============================================================================

/**
 * Generate the azure-ad-automator.ts module with multi-selector resilience
 */
export function generateAzureAdAutomatorModule(
  config: AzureAdSsoConfig,
): string {
  const { toolName, successUrlPatterns } = config;

  // Build success URL check logic
  const successPatterns =
    successUrlPatterns.length > 0
      ? successUrlPatterns.map((p) => `url.includes("${p}")`).join(" || ")
      : `url.includes("${toolName}") || url.includes("/nav") || url.includes("/home") || url.includes("/welcome")`;

  return `/**
 * Azure AD Automator for ${toolName} MCP
 *
 * Multi-selector resilient automation for Azure AD / Entra ID / Microsoft SSO login flows.
 * Tries multiple selectors for each field type to handle different Azure AD configurations.
 *
 * Generated by thesun with Azure AD SSO support.
 */

import type { Page } from "playwright";
import { Logger } from "./logger.js";
import { execFileNoThrow } from "./utils/exec-file-no-throw.js";

/**
 * Multi-selector patterns for Azure AD login flow.
 * Each field type has multiple possible selectors for resilience.
 */
const SELECTORS = {
  email: [
    'input[type="email"]',
    'input[name="loginfmt"]',
    'input[placeholder*="email" i]',
    'input[placeholder*="username" i]',
    "#i0116",
  ],
  emailNext: [
    'input[type="submit"][value="Next"]',
    'button:has-text("Next")',
    "#idSIButton9",
  ],
  password: [
    'input[type="password"]',
    'input[name="passwd"]',
    'input[placeholder*="password" i]',
    "#i0118",
  ],
  passwordNext: [
    'input[type="submit"][value="Sign in"]',
    'button:has-text("Sign in")',
    "#idSIButton9",
  ],
  mfaCode: [
    'input[name="otc"]',
    'input[type="tel"]',
    'input[placeholder*="code" i]',
    "#idTxtBx_SAOTCC_OTC",
  ],
  mfaVerify: [
    'input[type="submit"][value="Verify"]',
    'button:has-text("Verify")',
    "#idSubmit_SAOTCC_Continue",
  ],
  staySignedIn: [
    'input[type="submit"][value="Yes"]',
    'button:has-text("Yes")',
    "#idSIButton9",
  ],
  staySignedInNo: [
    'input[type="submit"][value="No"]',
    'button:has-text("No")',
  ],
  // Push MFA detection (Authenticator app, phone call)
  mfaPushPrompt: [
    'div:has-text("Approve sign in request")',
    'div:has-text("Open your Authenticator app")',
    'div:has-text("We\'ve sent a notification")',
    "#idDiv_SAOTCAS_Title",
    "#idRichContext_DisplaySign", // Number matching challenge
  ],
  mfaPhoneCall: [
    'div:has-text("We\'re calling")',
    'div:has-text("Answer the call")',
  ],
} as const;

export interface LoginCredentials {
  email: string;
  password: string;
  mfaScript: string;
}

/**
 * Discovered API headers from network interception
 */
export interface DiscoveredApiHeaders {
  csrfToken?: string;
  csrfHeaderName?: string;
  bearerToken?: string;
  customHeaders: Record<string, string>;
  contentType?: string;
}

export interface LoginResult {
  success: boolean;
  error?: string;
  cookies?: any[];
  requiresManualMfa?: boolean; // True when push MFA detected (Authenticator/phone)
  discoveredHeaders?: DiscoveredApiHeaders; // Headers captured from network traffic
}

export class AzureADAutomator {
  private logger: Logger;
  private instanceUrl: string | null = null;
  private capturedHeaders: Map<string, string> = new Map();
  private capturedApiCalls: Array<{ url: string; headers: Record<string, string> }> = [];

  constructor(logger: Logger) {
    this.logger = logger;
  }

  /**
   * Set up network interception to capture API headers
   */
  private async setupNetworkInterception(page: Page): Promise<void> {
    // Listen for all requests to capture headers
    page.on("request", (request) => {
      const url = request.url();
      const headers = request.headers();

      // Only capture XHR/fetch calls to the target app (not SSO pages)
      if (this.instanceUrl && url.includes(this.instanceUrl.replace(/^https?:\\/\\//, ""))) {
        // Skip static resources
        const resourceType = request.resourceType();
        if (["xhr", "fetch"].includes(resourceType) || url.includes("/api/")) {
          this.capturedApiCalls.push({ url, headers: { ...headers } });

          // Look for CSRF tokens in headers
          for (const [key, value] of Object.entries(headers)) {
            const lowerKey = key.toLowerCase();
            if (lowerKey.includes("csrf") || lowerKey.includes("xsrf") || lowerKey === "x-token") {
              this.capturedHeaders.set(key, value);
              this.logger.debug(\`Captured header: \${key}\`);
            }
            // Capture other interesting headers
            if (lowerKey === "x-requested-with" || lowerKey === "authorization" ||
                lowerKey.startsWith("x-") && !lowerKey.includes("forwarded")) {
              this.capturedHeaders.set(key, value);
            }
          }
        }
      }
    });

    this.logger.debug("Network interception enabled for API header discovery");
  }

  /**
   * Extract additional tokens from page context (localStorage, sessionStorage, window vars)
   */
  private async extractPageTokens(page: Page): Promise<Record<string, string>> {
    const tokens: Record<string, string> = {};

    try {
      const pageTokens = await page.evaluate(() => {
        const result: Record<string, string> = {};

        // Check window variables for CSRF/API tokens
        const tokenVars = [
          "g_ck", "csrfToken", "csrf_token", "_csrf", "xsrfToken",
          "apiToken", "api_token", "authToken", "__csrf_token__"
        ];

        for (const varName of tokenVars) {
          try {
            const win = window as any;
            if (win[varName]) {
              result[\`window.\${varName}\`] = String(win[varName]);
            }
            // Check common namespaces
            if (win.NOW && win.NOW[varName]) {
              result[\`NOW.\${varName}\`] = String(win.NOW[varName]);
            }
            if (win.__APP_STATE__ && win.__APP_STATE__[varName]) {
              result[\`__APP_STATE__.\${varName}\`] = String(win.__APP_STATE__[varName]);
            }
          } catch {}
        }

        // Check localStorage
        try {
          for (let i = 0; i < localStorage.length; i++) {
            const key = localStorage.key(i);
            if (key && (key.toLowerCase().includes("token") ||
                        key.toLowerCase().includes("csrf") ||
                        key.toLowerCase().includes("auth"))) {
              const value = localStorage.getItem(key);
              if (value && value.length < 500) { // Skip large values
                result[\`localStorage.\${key}\`] = value;
              }
            }
          }
        } catch {}

        // Check sessionStorage
        try {
          for (let i = 0; i < sessionStorage.length; i++) {
            const key = sessionStorage.key(i);
            if (key && (key.toLowerCase().includes("token") ||
                        key.toLowerCase().includes("csrf") ||
                        key.toLowerCase().includes("auth"))) {
              const value = sessionStorage.getItem(key);
              if (value && value.length < 500) {
                result[\`sessionStorage.\${key}\`] = value;
              }
            }
          }
        } catch {}

        // Check meta tags
        try {
          const csrfMeta = document.querySelector('meta[name="csrf-token"]');
          if (csrfMeta) {
            result["meta.csrf-token"] = csrfMeta.getAttribute("content") || "";
          }
          const xsrfMeta = document.querySelector('meta[name="_csrf"]');
          if (xsrfMeta) {
            result["meta._csrf"] = xsrfMeta.getAttribute("content") || "";
          }
        } catch {}

        return result;
      });

      Object.assign(tokens, pageTokens);
      this.logger.debug(\`Extracted \${Object.keys(pageTokens).length} page tokens\`);
    } catch (error) {
      this.logger.debug("Could not extract page tokens (may be expected)");
    }

    return tokens;
  }

  /**
   * Analyze captured traffic to determine required API headers
   */
  private analyzeDiscoveredHeaders(): DiscoveredApiHeaders {
    const result: DiscoveredApiHeaders = {
      customHeaders: {},
    };

    // Analyze captured headers
    for (const [key, value] of this.capturedHeaders.entries()) {
      const lowerKey = key.toLowerCase();

      if (lowerKey.includes("csrf") || lowerKey.includes("xsrf")) {
        result.csrfToken = value;
        result.csrfHeaderName = key;
      } else if (lowerKey === "authorization" && value.startsWith("Bearer ")) {
        result.bearerToken = value.replace("Bearer ", "");
      } else if (lowerKey === "x-requested-with") {
        result.customHeaders[key] = value;
      } else if (lowerKey.startsWith("x-") && value) {
        result.customHeaders[key] = value;
      }
    }

    // Analyze captured API calls for patterns
    if (this.capturedApiCalls.length > 0) {
      const contentTypes = new Set<string>();
      for (const call of this.capturedApiCalls) {
        const ct = call.headers["content-type"];
        if (ct) contentTypes.add(ct);
      }
      // Use most common content type
      if (contentTypes.size > 0) {
        result.contentType = [...contentTypes][0];
      }
    }

    this.logger.info(\`Discovered \${Object.keys(result.customHeaders).length} custom headers, CSRF: \${result.csrfToken ? "yes" : "no"}\`);

    return result;
  }

  /**
   * Main orchestration: perform complete Azure AD login
   */
  async performLogin(
    page: Page,
    credentials: LoginCredentials,
    timeout: number = 90000,
    instanceUrl?: string
  ): Promise<LoginResult> {
    this.instanceUrl = instanceUrl || null;
    this.capturedHeaders.clear();
    this.capturedApiCalls = [];

    try {
      this.logger.info("Starting Azure AD login automation");

      // Set up network interception BEFORE any navigation
      await this.setupNetworkInterception(page);

      // Step 1: Email field
      const emailFilled = await this.detectAndFillEmail(page, credentials.email, timeout);
      if (!emailFilled) {
        return { success: false, error: "Failed to detect or fill email field" };
      }

      // Step 2: Password field (may appear after email or on same page)
      await page.waitForTimeout(1000);
      const passwordFilled = await this.detectAndFillPassword(page, credentials.password, timeout);
      if (!passwordFilled) {
        return { success: false, error: "Failed to detect or fill password field" };
      }

      // Step 3: MFA code (may or may not appear)
      await page.waitForTimeout(1000);
      const mfaHandled = await this.detectAndFillMFA(page, credentials.mfaScript, timeout);
      if (mfaHandled === "push_mfa_detected") {
        return {
          success: false,
          error: "Push MFA detected - requires visible browser for manual approval",
          requiresManualMfa: true,
        };
      }
      if (!mfaHandled) {
        this.logger.warn("MFA handling failed or not required");
      }

      // Step 4: Handle "Stay signed in?" prompt
      await page.waitForTimeout(1000);
      await this.handleStaySignedIn(page, timeout);

      // Step 5: Wait for redirect to target service
      const redirected = await this.waitForSuccessRedirect(page, timeout);
      if (!redirected) {
        return { success: false, error: "Timeout waiting for redirect to target service" };
      }

      // Extract cookies for session persistence
      const cookies = await page.context().cookies();

      // Extract CSRF token from cookies if present
      // Common pattern: CSRF token in cookie must also be sent as header
      for (const cookie of cookies) {
        const name = cookie.name.toLowerCase();
        if (name.includes("csrf") || name.includes("xsrf") || name === "_csrf") {
          this.capturedHeaders.set(cookie.name, cookie.value);
          this.logger.debug(\`Found CSRF cookie: \${cookie.name}\`);
        }
      }

      // Wait a moment for any post-login API calls
      await page.waitForTimeout(2000);

      // Try to trigger a sample API call to capture required headers
      await this.triggerSampleApiCall(page);

      // Extract tokens from page context
      const pageTokens = await this.extractPageTokens(page);

      // Merge page tokens into captured headers
      for (const [key, value] of Object.entries(pageTokens)) {
        if (key.includes("csrf") || key.includes("token")) {
          // Store with a normalized key
          const headerKey = key.includes("csrf") ? "X-CSRFToken" : "X-Token";
          if (!this.capturedHeaders.has(headerKey)) {
            this.capturedHeaders.set(headerKey, value);
          }
        }
      }

      // Analyze all discovered headers
      const discoveredHeaders = this.analyzeDiscoveredHeaders();

      this.logger.info("Azure AD login completed successfully");
      this.logger.info(\`Discovered API requirements: \${JSON.stringify(discoveredHeaders)}\`);

      return { success: true, cookies, discoveredHeaders };
    } catch (error: any) {
      this.logger.error("Azure AD login failed", error);
      return { success: false, error: error.message || "Unknown error during login" };
    }
  }

  /**
   * Trigger a sample API call to capture the headers the app uses
   */
  private async triggerSampleApiCall(page: Page): Promise<void> {
    if (!this.instanceUrl) return;

    try {
      // Try clicking something that would trigger an API call
      // Or navigate to a page that loads data
      const currentUrl = page.url();

      // Wait for any lazy-loaded API calls
      await page.waitForLoadState("networkidle");

      // If we haven't captured any API calls yet, try to trigger one
      if (this.capturedApiCalls.length === 0) {
        this.logger.debug("No API calls captured yet, attempting to trigger one...");

        // Try common API endpoints to discover patterns
        const testEndpoints = [
          "/api/v2/settings",
          "/api/v1/config",
          "/api/now/table/sys_user?sysparm_limit=1",
          "/rest/api/latest/myself",
          "/api/me",
        ];

        for (const endpoint of testEndpoints) {
          try {
            // Use page.evaluate to make a fetch call and capture what headers the browser sends
            await page.evaluate(async (url: string) => {
              try {
                await fetch(url, { method: "GET", credentials: "include" });
              } catch {}
            }, this.instanceUrl + endpoint);
            await page.waitForTimeout(500);
          } catch {}
        }
      }

      this.logger.debug(\`Captured \${this.capturedApiCalls.length} API calls for header analysis\`);
    } catch (error) {
      this.logger.debug("Could not trigger sample API call (may be expected)");
    }
  }

  /**
   * Try multiple selectors with retries until one works
   */
  private async trySelectors(
    page: Page,
    selectors: readonly string[],
    timeout: number,
    action?: "click" | "fill",
    fillValue?: string
  ): Promise<boolean> {
    for (const selector of selectors) {
      try {
        this.logger.debug(\`Trying selector: \${selector}\`);
        const element = await page.waitForSelector(selector, {
          timeout: Math.min(timeout, 5000),
          state: "visible",
        });

        if (element) {
          if (action === "click") {
            await element.click();
            this.logger.debug(\`Clicked element: \${selector}\`);
          } else if (action === "fill" && fillValue !== undefined) {
            await element.fill(fillValue);
            this.logger.debug(\`Filled element: \${selector}\`);
          }
          return true;
        }
      } catch (error) {
        this.logger.debug(\`Selector failed: \${selector}\`);
        continue;
      }
    }
    return false;
  }

  /**
   * Try selectors with a custom per-selector timeout
   */
  private async trySelectorsWithTimeout(
    page: Page,
    selectors: readonly string[],
    timeoutPerSelector: number,
    action?: "click" | "fill",
    fillValue?: string
  ): Promise<boolean> {
    for (const selector of selectors) {
      try {
        this.logger.debug(\`Trying selector: \${selector}\`);
        const element = await page.waitForSelector(selector, {
          timeout: timeoutPerSelector,
          state: "visible",
        });

        if (element) {
          if (action === "click") {
            await element.click();
            this.logger.debug(\`Clicked element: \${selector}\`);
          } else if (action === "fill" && fillValue !== undefined) {
            await element.fill(fillValue);
            this.logger.debug(\`Filled element: \${selector}\`);
          }
          return true;
        }
      } catch (error) {
        this.logger.debug(\`Selector failed: \${selector}\`);
        continue;
      }
    }
    return false;
  }

  /**
   * Detect and fill email field, then click Next
   */
  private async detectAndFillEmail(page: Page, email: string, timeout: number): Promise<boolean> {
    this.logger.info("Detecting email field");

    const emailFilled = await this.trySelectors(page, SELECTORS.email, timeout, "fill", email);
    if (!emailFilled) {
      this.logger.error("No email field detected");
      return false;
    }

    this.logger.info("Email field filled");
    await page.waitForTimeout(500);

    const nextClicked = await this.trySelectors(page, SELECTORS.emailNext, timeout, "click");
    if (!nextClicked) {
      this.logger.warn("No email Next button found (combined flow?)");
      return true;
    }

    this.logger.info("Email Next button clicked");
    return true;
  }

  /**
   * Detect and fill password field, then click Sign in
   */
  private async detectAndFillPassword(page: Page, password: string, timeout: number): Promise<boolean> {
    this.logger.info("Detecting password field");

    const passwordFilled = await this.trySelectors(page, SELECTORS.password, timeout, "fill", password);
    if (!passwordFilled) {
      this.logger.error("No password field detected");
      return false;
    }

    this.logger.info("Password field filled");
    await page.waitForTimeout(500);

    const signinClicked = await this.trySelectors(page, SELECTORS.passwordNext, timeout, "click");
    if (!signinClicked) {
      this.logger.error("No Sign in button detected");
      return false;
    }

    this.logger.info("Sign in button clicked");
    return true;
  }

  /**
   * Detect push MFA (Authenticator app, phone call) that requires manual approval
   */
  private async detectPushMfa(page: Page): Promise<"push" | "phone" | null> {
    // Check page content for push MFA indicators
    const content = await page.content();

    const pushIndicators = [
      "Approve sign in request",
      "Open your Authenticator app",
      "We've sent a notification",
      "Microsoft Authenticator",
      "Approve the request",
    ];

    const phoneIndicators = [
      "We're calling",
      "Answer the call",
      "phone call",
    ];

    for (const indicator of phoneIndicators) {
      if (content.toLowerCase().includes(indicator.toLowerCase())) {
        return "phone";
      }
    }

    for (const indicator of pushIndicators) {
      if (content.toLowerCase().includes(indicator.toLowerCase())) {
        return "push";
      }
    }

    // Also check for number matching display
    for (const selector of SELECTORS.mfaPushPrompt) {
      try {
        const element = await page.$(selector);
        if (element) {
          return "push";
        }
      } catch {
        // Selector not found, continue
      }
    }

    return null;
  }

  /**
   * Detect MFA field, generate code via script, and submit
   * Returns "push_mfa_detected" if push MFA is detected (requires manual approval)
   */
  private async detectAndFillMFA(page: Page, mfaScript: string, timeout: number): Promise<boolean | "push_mfa_detected"> {
    this.logger.info("Checking for MFA prompts");

    // First check for push MFA (Authenticator app, phone call)
    const pushMfaType = await this.detectPushMfa(page);
    if (pushMfaType) {
      if (pushMfaType === "phone") {
        this.logger.warn("⚠️  Phone call MFA detected - requires manual approval!");
        this.logger.warn("   Please answer the phone call to complete authentication");
      } else {
        this.logger.warn("⚠️  Push/phone MFA detected - requires manual approval!");
        this.logger.warn("   Please check your Microsoft Authenticator app or phone");
      }
      return "push_mfa_detected";
    }

    const mfaFieldExists = await this.trySelectors(
      page,
      SELECTORS.mfaCode,
      Math.min(timeout, 10000)
    );

    if (!mfaFieldExists) {
      this.logger.info("No MFA field detected (may not be required)");
      return true;
    }

    if (!mfaScript || mfaScript.trim() === "") {
      this.logger.warn("MFA field detected but no MFA script configured - manual entry required");
      this.logger.warn("Waiting for manual MFA code entry...");
      return true;
    }

    this.logger.info("MFA field detected, generating code");

    const result = await execFileNoThrow(mfaScript, [], { timeout: 10000 });

    if (result.exitCode !== 0) {
      this.logger.error(\`MFA script failed: \${result.stderr || "Unknown error"}\`);
      return false;
    }

    const mfaCode = result.stdout.trim();
    if (!/^\\d{6}$/.test(mfaCode)) {
      this.logger.error(\`Invalid MFA code format: \${mfaCode}\`);
      return false;
    }

    this.logger.info("MFA code generated successfully");

    const mfaFilled = await this.trySelectors(page, SELECTORS.mfaCode, timeout, "fill", mfaCode);
    if (!mfaFilled) {
      this.logger.error("Failed to fill MFA code");
      return false;
    }

    this.logger.info("MFA code filled");
    await page.waitForTimeout(500);

    const verifyClicked = await this.trySelectors(page, SELECTORS.mfaVerify, timeout, "click");
    if (!verifyClicked) {
      this.logger.error("No Verify button detected");
      return false;
    }

    this.logger.info("MFA Verify button clicked");
    return true;
  }

  /**
   * Handle "Stay signed in?" prompt (click Yes by default)
   */
  private async handleStaySignedIn(page: Page, timeout: number): Promise<boolean> {
    this.logger.info("Checking for 'Stay signed in?' prompt");

    const yesClicked = await this.trySelectorsWithTimeout(
      page,
      SELECTORS.staySignedIn,
      8000,
      "click"
    );

    if (!yesClicked) {
      this.logger.info("No 'Stay signed in?' prompt detected");
      return true;
    }

    this.logger.info("'Stay signed in?' Yes button clicked");
    return true;
  }

  /**
   * Wait for redirect to target service (not a login page)
   */
  private async waitForSuccessRedirect(page: Page, timeout: number): Promise<boolean> {
    this.logger.info("Waiting for redirect to target service");

    try {
      const currentUrl = page.url();
      if (this.isSuccessUrl(currentUrl)) {
        this.logger.info(\`Already on target service: \${currentUrl}\`);
        return true;
      }

      await page.waitForURL((url) => this.isSuccessUrl(url.toString()), { timeout });
      this.logger.info(\`Redirected to target service: \${page.url()}\`);
      return true;
    } catch (error) {
      this.logger.error(\`Timeout waiting for redirect. Current URL: \${page.url()}\`);
      return false;
    }
  }

  /**
   * Check if URL indicates successful authentication (not a login page)
   */
  private isSuccessUrl(url: string): boolean {
    try {
      // Check if still on a login page
      const isLoginPage =
        url.includes("/login") ||
        url.includes("/saml") ||
        url.includes("/sso") ||
        url.includes("idp") ||
        url.includes("okta") ||
        url.includes("auth0") ||
        url.includes("login.microsoftonline") ||
        url.includes("adfs") ||
        url.includes("/oauth");

      if (isLoginPage) {
        return false;
      }

      // Check for success patterns
      return ${successPatterns};
    } catch {
      return false;
    }
  }
}
`;
}

// ============================================================================
// Code Generation - Logger Module
// ============================================================================

export function generateLoggerModule(): string {
  return `/**
 * Simple Logger for MCP
 *
 * Generated by thesun with Azure AD SSO support.
 */

export type LogLevel = "DEBUG" | "INFO" | "WARN" | "ERROR";

const LOG_LEVELS: Record<LogLevel, number> = {
  DEBUG: 0,
  INFO: 1,
  WARN: 2,
  ERROR: 3,
};

export class Logger {
  private level: LogLevel;

  constructor(level: LogLevel = "INFO") {
    this.level = level;
  }

  private shouldLog(level: LogLevel): boolean {
    return LOG_LEVELS[level] >= LOG_LEVELS[this.level];
  }

  debug(message: string, ...args: any[]): void {
    if (this.shouldLog("DEBUG")) {
      console.error(\`[DEBUG] \${message}\`, ...args);
    }
  }

  info(message: string, ...args: any[]): void {
    if (this.shouldLog("INFO")) {
      console.error(\`[INFO] \${message}\`, ...args);
    }
  }

  warn(message: string, ...args: any[]): void {
    if (this.shouldLog("WARN")) {
      console.error(\`[WARN] \${message}\`, ...args);
    }
  }

  error(message: string, ...args: any[]): void {
    if (this.shouldLog("ERROR")) {
      console.error(\`[ERROR] \${message}\`, ...args);
    }
  }
}
`;
}

// ============================================================================
// Code Generation - Exec File Utility
// ============================================================================

export function generateExecFileNoThrowModule(): string {
  return `/**
 * Safe command execution utility
 *
 * Generated by thesun with Azure AD SSO support.
 */

import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

export interface ExecResult {
  stdout: string;
  stderr: string;
  exitCode: number;
}

export async function execFileNoThrow(
  command: string,
  args: string[] = [],
  options: { timeout?: number } = {}
): Promise<ExecResult> {
  try {
    const { stdout, stderr } = await execFileAsync(command, args, {
      timeout: options.timeout || 30000,
      encoding: "utf-8",
    });
    return { stdout: stdout || "", stderr: stderr || "", exitCode: 0 };
  } catch (error: any) {
    return {
      stdout: error.stdout || "",
      stderr: error.stderr || error.message || "Unknown error",
      exitCode: error.code || 1,
    };
  }
}
`;
}

// ============================================================================
// Code Generation - Credential Store Module
// ============================================================================

export function generateCredentialStoreModule(
  config: AzureAdSsoConfig,
): string {
  const { toolName } = config;

  return `/**
 * Credential Store for ${toolName} MCP
 *
 * Securely stores passwords in the system keychain.
 *
 * Generated by thesun with Azure AD SSO support.
 */

import keytar from "keytar";

const SERVICE_NAME = "${toolName}-mcp";

export class CredentialStore {
  /**
   * Store password in system keychain
   */
  async setPassword(email: string, password: string): Promise<void> {
    await keytar.setPassword(SERVICE_NAME, email, password);
  }

  /**
   * Retrieve password from system keychain
   */
  async getPassword(email: string): Promise<string | null> {
    return await keytar.getPassword(SERVICE_NAME, email);
  }

  /**
   * Delete password from system keychain
   */
  async deletePassword(email: string): Promise<boolean> {
    return await keytar.deletePassword(SERVICE_NAME, email);
  }

  /**
   * Check if password exists for email
   */
  async hasPassword(email: string): Promise<boolean> {
    const password = await this.getPassword(email);
    return password !== null;
  }
}
`;
}

// ============================================================================
// Code Generation - Config Manager Module
// ============================================================================

export function generateConfigManagerModule(config: AzureAdSsoConfig): string {
  const { toolName } = config;

  return `/**
 * Config Manager for ${toolName} MCP
 *
 * Manages authentication configuration file with corruption detection and recovery.
 *
 * Features:
 * - Validates config structure on every load
 * - Detects corruption (e.g., JSON-in-field patterns)
 * - Auto-backup before every write
 * - Recovery from backup on corruption
 *
 * Generated by thesun with Azure AD SSO support.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, copyFileSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import type { LogLevel } from "./logger.js";

const CONFIG_DIR = join(homedir(), ".${toolName}-mcp");
const CONFIG_FILE = join(CONFIG_DIR, "config.json");
const CONFIG_BACKUP = join(CONFIG_DIR, "config.json.backup");

export interface AuthConfig {
  instanceUrl: string;
  email: string;
  mfaScript: string;
  headless: boolean;
  timeout: number;
  retryAttempts: number;
  logLevel: LogLevel;
}

export const DEFAULT_CONFIG: Partial<AuthConfig> = {
  mfaScript: "",
  headless: true,
  timeout: 90000,
  retryAttempts: 3,
  logLevel: "INFO",
};

export interface ConfigValidationError {
  field: string;
  value: string;
  message: string;
}

export interface ConfigValidationResult {
  valid: boolean;
  errors: ConfigValidationError[];
  corrupted: boolean;
  recoverable: boolean;
}

/**
 * Detect if a string looks like corrupted JSON (MCP protocol leak)
 */
function looksLikeCorruptedJson(value: string): boolean {
  if (!value || typeof value !== "string") return false;
  // Check for common corruption patterns
  return (
    value.includes('{"method":') ||
    value.includes('{"jsonrpc":') ||
    value.includes('"protocolVersion"') ||
    value.includes('"capabilities"') ||
    value.startsWith("{") && value.length > 100
  );
}

/**
 * Validate a config object
 */
function validateConfig(config: Partial<AuthConfig>): ConfigValidationResult {
  const errors: ConfigValidationError[] = [];
  let corrupted = false;

  // Validate email
  if (config.email) {
    if (!config.email.includes("@")) {
      errors.push({
        field: "email",
        value: config.email.substring(0, 50),
        message: "email must be a valid email address (missing @)",
      });
    }
    if (looksLikeCorruptedJson(config.email)) {
      errors.push({
        field: "email",
        value: config.email.substring(0, 50) + "...",
        message: "email field contains corrupted JSON data (MCP protocol leak detected)",
      });
      corrupted = true;
    }
  }

  // Validate instanceUrl
  if (config.instanceUrl) {
    if (!config.instanceUrl.startsWith("http://") && !config.instanceUrl.startsWith("https://")) {
      errors.push({
        field: "instanceUrl",
        value: config.instanceUrl.substring(0, 50),
        message: "instanceUrl must be a valid URL starting with http:// or https://",
      });
    }
    if (looksLikeCorruptedJson(config.instanceUrl)) {
      errors.push({
        field: "instanceUrl",
        value: config.instanceUrl.substring(0, 50) + "...",
        message: "instanceUrl field contains corrupted JSON data",
      });
      corrupted = true;
    }
  }

  // Check for backup
  const recoverable = existsSync(CONFIG_BACKUP);

  return {
    valid: errors.length === 0,
    errors,
    corrupted,
    recoverable,
  };
}

export class ConfigManager {
  private logger = console;

  /**
   * Load configuration from file with validation
   * @throws Error if config is corrupted and unrecoverable
   */
  load(): AuthConfig | null {
    if (!existsSync(CONFIG_FILE)) {
      return null;
    }

    try {
      const data = JSON.parse(readFileSync(CONFIG_FILE, "utf-8"));
      const config = { ...DEFAULT_CONFIG, ...data } as AuthConfig;

      // Validate the loaded config
      const validation = validateConfig(config);

      if (!validation.valid) {
        this.logger.error("Config validation failed:", validation.errors);

        if (validation.corrupted) {
          this.logger.error("⚠️  CONFIG CORRUPTION DETECTED!");

          // Attempt recovery from backup
          if (validation.recoverable) {
            this.logger.error("Attempting recovery from backup...");
            const recovered = this.attemptRecovery();
            if (recovered) {
              this.logger.error("✅ Config recovered from backup");
              return recovered;
            }
          }

          // Cannot recover - throw detailed error
          const errorDetails = validation.errors
            .map((e) => \`  - \${e.field}: \${e.message} (got: "\${e.value}")\`)
            .join("\\n");

          throw new Error(
            \`${toolName} MCP config corrupted!\\n\\n\` +
            \`Validation errors:\\n\${errorDetails}\\n\\n\` +
            \`This usually happens when MCP protocol data accidentally gets written to the config file.\\n\` +
            \`To fix: Run 'npm run setup' to reconfigure, or restore from backup:\\n\` +
            \`  cp ~/.${toolName}-mcp/config.json.backup ~/.${toolName}-mcp/config.json\`
          );
        }

        // Non-corruption validation errors - warn but continue
        this.logger.warn("Config has validation warnings:", validation.errors);
      }

      return config;
    } catch (error) {
      // Re-throw our corruption errors
      if (error instanceof Error && error.message.includes("corrupted")) {
        throw error;
      }
      this.logger.error(\`Failed to parse config: \${error}\`);
      return null;
    }
  }

  /**
   * Save configuration to file with validation and backup
   * @throws Error if trying to save corrupted config
   */
  save(config: AuthConfig): void {
    // Validate before saving
    const validation = validateConfig(config);

    if (!validation.valid) {
      const errorDetails = validation.errors
        .map((e) => \`\${e.field}: \${e.message}\`)
        .join(", ");

      throw new Error(
        \`Cannot save invalid config: \${errorDetails}. \` +
        \`This prevents config corruption.\`
      );
    }

    // Ensure directory exists
    if (!existsSync(CONFIG_DIR)) {
      mkdirSync(CONFIG_DIR, { recursive: true });
    }

    // Backup existing config before writing
    if (existsSync(CONFIG_FILE)) {
      try {
        copyFileSync(CONFIG_FILE, CONFIG_BACKUP);
        this.logger.error(\`Config backed up to \${CONFIG_BACKUP}\`);
      } catch (backupError) {
        this.logger.warn("Failed to backup config, continuing with save:", backupError);
      }
    }

    // Write new config
    writeFileSync(CONFIG_FILE, JSON.stringify(config, null, 2));
  }

  /**
   * Attempt to recover config from backup
   */
  attemptRecovery(): AuthConfig | null {
    if (!existsSync(CONFIG_BACKUP)) {
      return null;
    }

    try {
      const backupData = JSON.parse(readFileSync(CONFIG_BACKUP, "utf-8"));
      const backupConfig = { ...DEFAULT_CONFIG, ...backupData } as AuthConfig;

      // Validate backup
      const validation = validateConfig(backupConfig);
      if (validation.valid) {
        // Restore from backup
        copyFileSync(CONFIG_BACKUP, CONFIG_FILE);
        return backupConfig;
      }

      this.logger.error("Backup config is also invalid:", validation.errors);
      return null;
    } catch (error) {
      this.logger.error("Failed to recover from backup:", error);
      return null;
    }
  }

  /**
   * Get config directory path
   */
  getConfigDir(): string {
    return CONFIG_DIR;
  }

  /**
   * Get config file path
   */
  getConfigPath(): string {
    return CONFIG_FILE;
  }

  /**
   * Get backup file path
   */
  getBackupPath(): string {
    return CONFIG_BACKUP;
  }

  /**
   * Clear corrupted config and backup
   */
  clearConfig(): void {
    try {
      if (existsSync(CONFIG_FILE)) {
        unlinkSync(CONFIG_FILE);
      }
      if (existsSync(CONFIG_BACKUP)) {
        unlinkSync(CONFIG_BACKUP);
      }
    } catch (error) {
      this.logger.error("Failed to clear config:", error);
    }
  }
}
`;
}

// ============================================================================
// Code Generation - Hermes Dual-Mode Azure AD Auth (thin wrapper)
// ============================================================================

/**
 * Generate a thin Azure AD auth module that delegates to @hermes/auth-core.
 * Replaces the 500+ line inlined browser automation with ~40 lines.
 */
function generateHermesAzureAdAuth(config: AzureAdSsoConfig): string {
  const { toolName, successUrlPatterns } = config;
  const envPrefix = toolName.toUpperCase().replace(/-/g, "_");
  const patterns = successUrlPatterns.length > 0
    ? JSON.stringify(successUrlPatterns)
    : JSON.stringify([toolName, "/nav", "/home", "/welcome"]);

  return `/**
 * Azure AD SSO Authentication for ${toolName} MCP (Hermes dual-mode)
 *
 * When HERMES_URL is set, tokens come from the Hermes auth broker.
 * Otherwise, PlaywrightBrowserAuth from @hermes/auth-core runs the SSO flow locally.
 *
 * Generated by thesun with @hermes/auth-core dual-mode support.
 */
import { getToken } from '@hermes/auth-core';
import type { DualModeAuthOptions } from '@hermes/auth-core';

let cachedToken: string | null = null;
let tokenExpiry = 0;

export async function authenticate(): Promise<string> {
  if (cachedToken && Date.now() < tokenExpiry - 60_000) return cachedToken;

  const opts: DualModeAuthOptions = {
    service: '${toolName}',
    scheme: 'azure_ad_sso',
    standaloneAcquire: async () => {
      const { PlaywrightBrowserAuth, createCredentialStore } = await import('@hermes/auth-core');
      const store = await createCredentialStore();
      const browser = new PlaywrightBrowserAuth({
        loginUrl: process.env.${envPrefix}_INSTANCE_URL ?? process.env.${envPrefix}_LOGIN_URL ?? '',
        successPatterns: ${patterns},
      });
      const result = await browser.acquire({
        credentialStore: store,
        service: '${toolName}',
      });
      return { accessToken: result.accessToken, expiresAt: result.expiresAt ?? Date.now() + 3600_000 };
    },
  };

  cachedToken = await getToken(opts);
  tokenExpiry = Date.now() + 3600_000;
  return cachedToken;
}

export async function getAuthHeaders(): Promise<Record<string, string>> {
  const token = await authenticate();
  return { Authorization: \`Bearer \${token}\` };
}

export async function initializeAuth(): Promise<void> {
  console.log('[Auth] Initializing Azure AD SSO dual-mode auth for ${toolName}');
  console.log('[Auth] HERMES_URL:', process.env.HERMES_URL ? 'set (broker mode)' : 'unset (standalone mode)');
  try {
    await authenticate();
    console.log('[Auth] Authentication initialized successfully');
  } catch (error) {
    console.error('[Auth] Failed to initialize:', error instanceof Error ? error.message : String(error));
    throw error;
  }
}
`;
}

// ============================================================================
// Code Generation - Robust Auth Module (legacy inlined)
// ============================================================================

/**
 * Generate the robust-auth.ts module for a new MCP.
 *
 * When hermesMode is 'auto', generates a thin wrapper using @hermes/auth-core
 * instead of the full 500+ line inlined browser automation.
 */
export function generateRobustAuthModule(
  config: AzureAdSsoConfig,
  hermesMode?: "auto" | "legacy",
): string {
  if (hermesMode === "auto") {
    return generateHermesAzureAdAuth(config);
  }

  const { toolName, headlessTimeout, visibleTimeout, cookieMaxAge } = config;

  return `/**
 * Robust Authentication Module for ${toolName} MCP
 *
 * Features:
 * - Automatic 401 detection and re-authentication
 * - Headless-first with automatic fallback to visible browser
 * - Proper timeouts to prevent hanging
 * - Browser process cleanup
 * - Credential auto-loading from config/keychain
 *
 * Generated by thesun with Azure AD SSO support.
 */

import { firefox, Browser } from "playwright";
import { existsSync, readFileSync, writeFileSync, mkdirSync, unlinkSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import keytar from "keytar";
import { ConfigManager } from "./auth-config.js";
import { CredentialStore } from "./credential-store.js";
import { AzureADAutomator } from "./azure-ad-automator.js";
import { Logger } from "./logger.js";

const CONFIG_DIR = join(homedir(), ".${toolName}-mcp");
const COOKIE_FILE = join(CONFIG_DIR, "cookies.json");

// Global SSO Store paths
const GLOBAL_SSO_FILE = join(homedir(), ".thesun", "sso", "credentials.json");
const GLOBAL_KEYCHAIN_SERVICE = "thesun-sso";

interface GlobalSsoCredential {
  realm: string;
  email: string;
  passwordKeychainKey: string;
  mfaScript?: string;
}

function extractRealm(email: string): string | null {
  const atIndex = email.indexOf("@");
  return atIndex > 0 ? email.substring(atIndex + 1).toLowerCase() : null;
}

async function getGlobalCredentials(realm: string): Promise<{ credential: GlobalSsoCredential; password: string } | null> {
  try {
    if (!existsSync(GLOBAL_SSO_FILE)) return null;

    const data = JSON.parse(readFileSync(GLOBAL_SSO_FILE, "utf-8"));
    const cred = (data.credentials || []).find(
      (c: GlobalSsoCredential) => c.realm.toLowerCase() === realm.toLowerCase()
    );

    if (!cred) return null;

    const password = await keytar.getPassword(GLOBAL_KEYCHAIN_SERVICE, cred.passwordKeychainKey);
    if (!password) return null;

    return { credential: cred, password };
  } catch {
    return null;
  }
}

// Timeouts
const HEADLESS_AUTH_TIMEOUT = ${headlessTimeout};
const VISIBLE_AUTH_TIMEOUT = ${visibleTimeout};
const NAVIGATION_TIMEOUT = 30000;
const COOKIE_MAX_AGE = ${cookieMaxAge};

export interface RobustAuthResult {
  success: boolean;
  cookies?: string;
  userToken?: string;
  instanceUrl?: string;
  error?: string;
  method?: "headless" | "visible" | "cached";
  discoveredHeaders?: {
    csrfToken?: string;
    csrfHeaderName?: string;
    bearerToken?: string;
    customHeaders: Record<string, string>;
    contentType?: string;
  };
}

/**
 * Load credentials from config and keychain
 * Throws if config is corrupted (with recovery instructions)
 */
async function loadCredentials(): Promise<{
  email: string;
  password: string;
  mfaScript: string;
  instanceUrl: string;
  headless: boolean;
} | null> {
  const configManager = new ConfigManager();

  // This will throw with detailed error if config is corrupted
  let config;
  try {
    config = configManager.load();
  } catch (error) {
    // Re-throw corruption errors with clear instructions
    if (error instanceof Error && error.message.includes("corrupted")) {
      throw error;
    }
    console.error("Failed to load config:", error);
    return null;
  }

  if (!config) {
    return null;
  }

  // Double-check email is valid (defense in depth)
  if (!config.email || !config.email.includes("@")) {
    throw new Error(
      \`Config corrupted: email field is invalid ("\${config.email?.substring(0, 30) || "(empty)"}").\\n\` +
      \`Run 'npm run setup' to reconfigure.\`
    );
  }

  const credentialStore = new CredentialStore();
  let password = await credentialStore.getPassword(config.email);
  let mfaScript = config.mfaScript || "";

  // If no local password, try global SSO store
  if (!password) {
    const realm = extractRealm(config.email);
    if (realm) {
      const globalCreds = await getGlobalCredentials(realm);
      if (globalCreds) {
        console.error(\`ℹ️  Using global SSO credentials for \${realm}\`);
        password = globalCreds.password;
        mfaScript = globalCreds.credential.mfaScript || mfaScript;
      }
    }
  }

  if (!password) {
    return null;
  }

  return {
    email: config.email,
    password: password,
    mfaScript: mfaScript,
    instanceUrl: config.instanceUrl,
    headless: config.headless ?? true,
  };
}

/**
 * Load cached cookies if valid
 */
function loadCachedCookies(): RobustAuthResult | null {
  if (!existsSync(COOKIE_FILE)) {
    return null;
  }

  try {
    const data = JSON.parse(readFileSync(COOKIE_FILE, "utf-8"));
    const timestamp = new Date(data.timestamp);
    const age = Date.now() - timestamp.getTime();

    if (age > COOKIE_MAX_AGE) {
      console.error("⚠️  Cached cookies expired");
      return null;
    }

    const cookieString = data.cookies
      .map((c: any) => \`\${c.name}=\${c.value}\`)
      .join("; ");

    return {
      success: true,
      cookies: cookieString,
      userToken: data.userToken || "",
      instanceUrl: data.instanceUrl,
      method: "cached",
      discoveredHeaders: data.discoveredHeaders || { customHeaders: {} },
    };
  } catch {
    return null;
  }
}

/**
 * Save cookies and discovered headers to cache
 */
function saveCookies(
  instanceUrl: string,
  cookies: any[],
  userToken?: string,
  discoveredHeaders?: RobustAuthResult["discoveredHeaders"]
): void {
  if (!existsSync(CONFIG_DIR)) {
    mkdirSync(CONFIG_DIR, { recursive: true });
  }

  const data = {
    instanceUrl,
    cookies,
    userToken: userToken || "",
    discoveredHeaders: discoveredHeaders || { customHeaders: {} },
    timestamp: new Date().toISOString(),
    source: "robust-auth",
  };

  writeFileSync(COOKIE_FILE, JSON.stringify(data, null, 2));
  console.error(\`✅ Cookies saved (\${cookies.length} cookies)\`);
  if (discoveredHeaders?.csrfToken) {
    console.error(\`✅ CSRF token captured: \${discoveredHeaders.csrfHeaderName}\`);
  }
  if (Object.keys(discoveredHeaders?.customHeaders || {}).length > 0) {
    console.error(\`✅ Custom headers captured: \${Object.keys(discoveredHeaders!.customHeaders).join(", ")}\`);
  }
}

/**
 * Clear cached cookies
 */
function clearCookies(): void {
  if (existsSync(COOKIE_FILE)) {
    try {
      unlinkSync(COOKIE_FILE);
    } catch {
      // Ignore errors
    }
  }
}

/**
 * Perform authentication with proper timeout and cleanup
 */
async function performAuth(
  instanceUrl: string,
  credentials: { email: string; password: string; mfaScript: string },
  headless: boolean,
  timeout: number,
  logger: Logger
): Promise<RobustAuthResult> {
  let browser: Browser | null = null;

  try {
    logger.info(\`Starting \${headless ? "headless" : "visible"} authentication...\`);

    browser = await firefox.launch({
      headless,
      timeout: 30000,
      firefoxUserPrefs: {
        "security.default_personal_cert": "Select Automatically",
      },
    });

    const context = await browser.newContext({
      viewport: { width: 1280, height: 800 },
    });

    const page = await context.newPage();

    await page.goto(instanceUrl, {
      waitUntil: "networkidle",
      timeout: NAVIGATION_TIMEOUT,
    });

    const automator = new AzureADAutomator(logger);

    const authPromise = automator.performLogin(page, credentials, timeout, instanceUrl);
    const timeoutPromise = new Promise<never>((_, reject) => {
      setTimeout(() => reject(new Error("Authentication timeout")), timeout);
    });

    const result = await Promise.race([authPromise, timeoutPromise]);

    if (result.success && result.cookies) {
      let userToken = "";
      try {
        userToken = await page.evaluate(() => {
          return (window as any).g_ck || (window as any).NOW?.g_ck || "";
        });
      } catch {
        // Ignore token extraction errors
      }

      // Get discovered headers from the login result
      const discoveredHeaders = result.discoveredHeaders || { customHeaders: {} };

      saveCookies(instanceUrl, result.cookies, userToken, discoveredHeaders);

      const cookieString = result.cookies
        .map((c: any) => \`\${c.name}=\${c.value}\`)
        .join("; ");

      return {
        success: true,
        cookies: cookieString,
        userToken,
        instanceUrl,
        method: headless ? "headless" : "visible",
        discoveredHeaders,
      };
    }

    return { success: false, error: result.error || "Authentication failed" };
  } catch (error: any) {
    return { success: false, error: error.message };
  } finally {
    if (browser) {
      try {
        await browser.close();
      } catch {
        // Ignore close errors
      }
    }
  }
}

/**
 * Main robust authentication function
 *
 * 1. Try cached cookies first
 * 2. Try headless authentication
 * 3. Fall back to visible browser if headless fails
 */
export async function robustAuthenticate(instanceUrl?: string): Promise<RobustAuthResult> {
  const logger = new Logger("INFO");

  // Load credentials - this will throw if config is corrupted
  let creds;
  try {
    creds = await loadCredentials();
  } catch (error) {
    // If config is corrupted, return detailed error
    if (error instanceof Error) {
      return {
        success: false,
        error: error.message,
      };
    }
    return {
      success: false,
      error: "Failed to load credentials: Unknown error",
    };
  }

  if (!creds) {
    return {
      success: false,
      error: "No credentials configured. Run 'npm run setup' first.",
    };
  }

  const targetUrl = instanceUrl || creds.instanceUrl;
  logger.info(\`🔐 Authenticating to \${targetUrl}\`);

  const cached = loadCachedCookies();
  if (cached && cached.success) {
    logger.info("✅ Using cached cookies");
    return cached;
  }

  logger.info("🔄 Attempting headless authentication...");
  const headlessResult = await performAuth(targetUrl, creds, true, HEADLESS_AUTH_TIMEOUT, logger);

  if (headlessResult.success) {
    logger.info("✅ Headless authentication successful!");
    return headlessResult;
  }

  logger.warn(\`⚠️  Headless auth failed: \${headlessResult.error}\`);
  logger.info("🌐 Opening visible browser for manual authentication...");

  const visibleResult = await performAuth(targetUrl, creds, false, VISIBLE_AUTH_TIMEOUT, logger);

  if (visibleResult.success) {
    logger.info("✅ Visible browser authentication successful!");
    return visibleResult;
  }

  return {
    success: false,
    error: \`Authentication failed. Headless: \${headlessResult.error}. Visible: \${visibleResult.error}\`,
  };
}

/**
 * Handle 401 error by re-authenticating
 */
export async function handleAuthFailure(): Promise<RobustAuthResult> {
  console.error("\\n⚠️  401 Unauthorized - Re-authenticating...\\n");
  clearCookies();
  return robustAuthenticate();
}

/**
 * Validate current session
 */
export async function validateSession(instanceUrl: string, cookies: string): Promise<boolean> {
  try {
    const response = await fetch(\`\${instanceUrl}/api/now/table/sys_user?sysparm_limit=1\`, {
      headers: {
        Cookie: cookies,
        Accept: "application/json",
      },
    });
    return response.status === 200;
  } catch {
    return false;
  }
}

/**
 * Get authentication headers for API requests
 *
 * Returns ALL required headers discovered during authentication:
 * - Cookie: Session cookies
 * - CSRF token: If discovered (with correct header name)
 * - Bearer token: If discovered
 * - Custom headers: Any other headers captured from API traffic
 */
export async function getAuthHeaders(): Promise<Record<string, string>> {
  const result = await robustAuthenticate();

  if (!result.success) {
    throw new Error(result.error || "Authentication failed");
  }

  const headers: Record<string, string> = {};

  // Add cookies
  if (result.cookies) {
    headers["Cookie"] = result.cookies;
  }

  // Add user token (ServiceNow-specific but harmless for others)
  if (result.userToken) {
    headers["x-usertoken"] = result.userToken;
  }

  // Add discovered CSRF token
  if (result.discoveredHeaders?.csrfToken) {
    const headerName = result.discoveredHeaders.csrfHeaderName || "X-CSRFToken";
    headers[headerName] = result.discoveredHeaders.csrfToken;
    console.error(\`✅ Using CSRF header: \${headerName}\`);
  }

  // Add bearer token if discovered
  if (result.discoveredHeaders?.bearerToken) {
    headers["Authorization"] = \`Bearer \${result.discoveredHeaders.bearerToken}\`;
  }

  // Add all custom headers discovered from traffic
  if (result.discoveredHeaders?.customHeaders) {
    for (const [key, value] of Object.entries(result.discoveredHeaders.customHeaders)) {
      headers[key] = value;
    }
  }

  // Add X-Requested-With if not already present (common requirement)
  if (!headers["X-Requested-With"]) {
    headers["X-Requested-With"] = "XMLHttpRequest";
  }

  // Add content type if discovered
  if (result.discoveredHeaders?.contentType) {
    headers["Content-Type"] = result.discoveredHeaders.contentType;
  }

  return headers;
}
`;
}

// ============================================================================
// Code Generation - Setup Wizard
// ============================================================================

/**
 * Generate the setup wizard (CLI script) with full UX
 */
export function generateSetupWizardModule(config: AzureAdSsoConfig): string {
  const { toolName } = config;
  const envPrefix = toolName.toUpperCase().replace(/-/g, "_");

  return `#!/usr/bin/env node
/**
 * ${toolName} MCP Setup Wizard
 *
 * Interactive setup for Azure AD SSO authentication.
 * Stores credentials securely in system keychain.
 * Supports global SSO credential sharing across MCPs.
 *
 * Generated by thesun.
 */

import prompts from "prompts";
import chalk from "chalk";
import ora from "ora";
import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import keytar from "keytar";
import { CredentialStore } from "../credential-store.js";
import { ConfigManager, DEFAULT_CONFIG } from "../auth-config.js";
import { execFileNoThrow } from "../utils/exec-file-no-throw.js";
import { firefox } from "playwright";
import { AzureADAutomator } from "../azure-ad-automator.js";
import { Logger } from "../logger.js";

// Global SSO Store integration
const GLOBAL_SSO_DIR = join(homedir(), ".thesun", "sso");
const GLOBAL_SSO_FILE = join(GLOBAL_SSO_DIR, "credentials.json");
const GLOBAL_KEYCHAIN_SERVICE = "thesun-sso";

interface GlobalSsoCredential {
  realm: string;
  email: string;
  passwordKeychainKey: string;
  mfaScript?: string;
  idpType: string;
  createdAt: string;
  lastUsed: string;
}

function extractRealm(email: string): string | null {
  const atIndex = email.indexOf("@");
  return atIndex > 0 ? email.substring(atIndex + 1).toLowerCase() : null;
}

async function getGlobalCredentials(realm: string): Promise<{ credential: GlobalSsoCredential; password: string } | null> {
  try {
    if (!existsSync(GLOBAL_SSO_FILE)) return null;

    const data = JSON.parse(readFileSync(GLOBAL_SSO_FILE, "utf-8"));
    const cred = (data.credentials || []).find(
      (c: GlobalSsoCredential) => c.realm.toLowerCase() === realm.toLowerCase()
    );

    if (!cred) return null;

    const password = await keytar.getPassword(GLOBAL_KEYCHAIN_SERVICE, cred.passwordKeychainKey);
    if (!password) return null;

    return { credential: cred, password };
  } catch {
    return null;
  }
}

async function saveGlobalCredentials(
  email: string,
  password: string,
  mfaScript?: string
): Promise<void> {
  const realm = extractRealm(email);
  if (!realm) return;

  if (!existsSync(GLOBAL_SSO_DIR)) {
    mkdirSync(GLOBAL_SSO_DIR, { recursive: true });
  }

  let data = { version: 1, credentials: [], updatedAt: new Date().toISOString() };
  try {
    if (existsSync(GLOBAL_SSO_FILE)) {
      data = JSON.parse(readFileSync(GLOBAL_SSO_FILE, "utf-8"));
    }
  } catch {}

  const keychainKey = \`\${realm}-\${email}\`;

  // Store password in global keychain
  await keytar.setPassword(GLOBAL_KEYCHAIN_SERVICE, keychainKey, password);

  // Update or add credential
  const existingIndex = data.credentials.findIndex(
    (c: GlobalSsoCredential) => c.realm.toLowerCase() === realm.toLowerCase()
  );

  const credential: GlobalSsoCredential = {
    realm,
    email,
    passwordKeychainKey: keychainKey,
    mfaScript,
    idpType: "azure-ad",
    createdAt: new Date().toISOString(),
    lastUsed: new Date().toISOString(),
  };

  if (existingIndex >= 0) {
    data.credentials[existingIndex] = credential;
  } else {
    data.credentials.push(credential);
  }

  data.updatedAt = new Date().toISOString();
  writeFileSync(GLOBAL_SSO_FILE, JSON.stringify(data, null, 2));
}

async function main() {
  console.log(chalk.bold.blue("\\n🔧 ${toolName} MCP Setup Wizard\\n"));
  console.log(chalk.dim("This wizard will guide you through the initial configuration.\\n"));

  const credentialStore = new CredentialStore();
  const configManager = new ConfigManager();

  // Check if already configured
  const existingConfig = configManager.load();
  if (existingConfig) {
    const { confirmReconfigure } = await prompts({
      type: "confirm",
      name: "confirmReconfigure",
      message: "Configuration already exists. Do you want to reconfigure?",
      initial: false,
    });

    if (!confirmReconfigure) {
      console.log(chalk.yellow("\\nSetup cancelled. Existing configuration preserved.\\n"));
      process.exit(0);
    }
  }

  // Step 1: Instance URL
  const { instanceUrl } = await prompts({
    type: "text",
    name: "instanceUrl",
    message: "${toolName} URL (e.g., https://your-instance.example.com):",
    validate: (value) => {
      if (!value) return "URL is required";
      if (!value.startsWith("https://")) return "URL must start with https://";
      return true;
    },
  });

  if (!instanceUrl) {
    console.log(chalk.red("\\n❌ Setup cancelled. URL is required.\\n"));
    process.exit(1);
  }

  // Step 2: Email
  const { email } = await prompts({
    type: "text",
    name: "email",
    message: "Your email address:",
    validate: (value) => {
      if (!value) return "Email is required";
      if (!value.includes("@")) return "Invalid email format";
      return true;
    },
  });

  if (!email) {
    console.log(chalk.red("\\n❌ Setup cancelled. Email is required.\\n"));
    process.exit(1);
  }

  // Step 2.5: Check for existing global SSO credentials
  const realm = extractRealm(email);
  let password = "";
  let mfaScript = "";
  let useGlobalCreds = false;

  if (realm) {
    const globalCreds = await getGlobalCredentials(realm);
    if (globalCreds) {
      console.log(chalk.green(\`\\n✨ Found existing SSO credentials for \${realm}!\\n\`));

      const { useExisting } = await prompts({
        type: "confirm",
        name: "useExisting",
        message: \`Use existing credentials for \${globalCreds.credential.email}?\`,
        initial: true,
      });

      if (useExisting) {
        password = globalCreds.password;
        mfaScript = globalCreds.credential.mfaScript || "";
        useGlobalCreds = true;
        console.log(chalk.dim("Using global SSO credentials...\\n"));
      }
    }
  }

  // Step 3: Password (if not using global creds)
  if (!useGlobalCreds) {
    const { inputPassword } = await prompts({
      type: "password",
      name: "inputPassword",
      message: "Your password:",
      validate: (value) => {
        if (!value) return "Password is required";
        if (value.length < 8) return "Password must be at least 8 characters";
        return true;
      },
    });

    if (!inputPassword) {
      console.log(chalk.red("\\n❌ Setup cancelled. Password is required.\\n"));
      process.exit(1);
    }
    password = inputPassword;

    // Step 4: Store credentials in local keychain
    const storeSpinner = ora("Storing credentials in system keychain").start();
    try {
      await credentialStore.setPassword(email, password);
      storeSpinner.succeed(chalk.green("Credentials stored securely in keychain"));
    } catch (error: any) {
      storeSpinner.fail(chalk.red("Failed to store credentials"));
      console.error(chalk.red(\`Error: \${error.message}\\n\`));
      process.exit(1);
    }

    // Step 5: MFA script (optional)
    const { inputMfaScript } = await prompts({
      type: "text",
      name: "inputMfaScript",
      message: "Path to MFA TOTP script (leave empty to skip):",
      initial: "",
      validate: (value) => {
        if (!value) return true;
        if (!existsSync(value)) return \`File not found: \${value}\`;
        return true;
      },
    });

    if (inputMfaScript) {
      mfaScript = inputMfaScript;

      // Step 6: Test MFA script
      const mfaTestSpinner = ora("Testing MFA script execution").start();
      try {
        const result = await execFileNoThrow(mfaScript, [], { timeout: 10000 });

        if (result.exitCode !== 0) {
          mfaTestSpinner.fail(chalk.red("MFA script execution failed"));
          console.error(chalk.red(\`Error: \${result.stderr || "Unknown error"}\\n\`));
          console.log(chalk.yellow("Please ensure your MFA script is executable and outputs a 6-digit TOTP code.\\n"));
          process.exit(1);
        }

        const mfaCode = result.stdout.trim();
        if (!/^\\d{6}$/.test(mfaCode)) {
          mfaTestSpinner.fail(chalk.red("Invalid MFA code format"));
          console.error(chalk.red(\`Expected 6-digit code, got: \${mfaCode.length > 0 ? mfaCode : "(empty)"}\\n\`));
          process.exit(1);
        }

        mfaTestSpinner.succeed(chalk.green(\`MFA script working correctly (generated: \${mfaCode})\`));
      } catch (error: any) {
        mfaTestSpinner.fail(chalk.red("Failed to test MFA script"));
        console.error(chalk.red(\`Error: \${error.message}\\n\`));
        process.exit(1);
      }
    } else {
      console.log(chalk.yellow("⚠️  Skipping MFA configuration (manual entry will be required during authentication)\\n"));
    }
  }

  // Step 7: Save configuration
  const saveSpinner = ora("Saving configuration").start();
  try {
    const config = {
      instanceUrl: instanceUrl.replace(/\\/$/, ""),
      email,
      mfaScript: mfaScript || "",
      headless: true,
      timeout: 90000,
      retryAttempts: 3,
      logLevel: "INFO" as const,
    };

    configManager.save(config);
    saveSpinner.succeed(chalk.green("Configuration saved successfully"));
  } catch (error: any) {
    saveSpinner.fail(chalk.red("Failed to save configuration"));
    console.error(chalk.red(\`Error: \${error.message}\\n\`));
    process.exit(1);
  }

  // Step 8: Test authentication
  console.log();
  const { testAuth } = await prompts({
    type: "confirm",
    name: "testAuth",
    message: "Would you like to test the authentication flow now?",
    initial: true,
  });

  if (testAuth) {
    console.log();
    const testSpinner = ora("Testing full authentication flow").start();

    try {
      const logger = new Logger("INFO");

      console.log(chalk.dim("  Attempting background authentication...\\n"));
      const browser = await firefox.launch({
        headless: true,
        firefoxUserPrefs: {
          "security.default_personal_cert": "Select Automatically",
        },
      });
      const context = await browser.newContext();
      const page = await context.newPage();

      await page.goto(instanceUrl, { waitUntil: "networkidle", timeout: 60000 });

      const automator = new AzureADAutomator(logger);
      const result = await automator.performLogin(
        page,
        { email, password, mfaScript: mfaScript || "" },
        90000,
        instanceUrl
      );

      if (result.success && result.cookies) {
        const cookieDir = configManager.getConfigDir();
        const cookieFile = join(cookieDir, "cookies.json");

        if (!existsSync(cookieDir)) {
          mkdirSync(cookieDir, { recursive: true });
        }

        const cookieData = {
          instanceUrl,
          cookies: result.cookies,
          timestamp: new Date().toISOString(),
          source: "automated-setup",
        };

        writeFileSync(cookieFile, JSON.stringify(cookieData, null, 2));
      }

      await browser.close();

      if (result.success) {
        testSpinner.succeed(chalk.green("Background authentication successful!"));
        console.log(chalk.green(\`\\n✅ Setup complete! Captured \${result.cookies?.length || 0} session cookies.\\n\`));
      } else {
        testSpinner.warn(chalk.yellow("Background authentication failed. Opening browser for manual login..."));
        console.log(chalk.dim(\`  \${result.error}\\n\`));

        try {
          const visibleBrowser = await firefox.launch({
            headless: false,
            firefoxUserPrefs: {
              "security.default_personal_cert": "Select Automatically",
            },
          });
          const visibleContext = await visibleBrowser.newContext();
          const visiblePage = await visibleContext.newPage();

          await visiblePage.goto(instanceUrl, { waitUntil: "networkidle", timeout: 60000 });

          const visibleAutomator = new AzureADAutomator(logger);
          const visibleResult = await visibleAutomator.performLogin(
            visiblePage,
            { email, password, mfaScript: mfaScript || "" },
            90000,
            instanceUrl
          );

          if (visibleResult.success && visibleResult.cookies) {
            const cookieDir = configManager.getConfigDir();
            const cookieFile = join(cookieDir, "cookies.json");

            if (!existsSync(cookieDir)) {
              mkdirSync(cookieDir, { recursive: true });
            }

            const cookieData = {
              instanceUrl,
              cookies: visibleResult.cookies,
              timestamp: new Date().toISOString(),
              source: "automated-setup-visible",
            };

            writeFileSync(cookieFile, JSON.stringify(cookieData, null, 2));
          }

          await visibleBrowser.close();

          if (visibleResult.success) {
            console.log(chalk.green(\`\\n✅ Setup complete! Captured \${visibleResult.cookies?.length || 0} session cookies.\\n\`));
          } else {
            console.error(chalk.red(\`\\n❌ Authentication failed: \${visibleResult.error}\\n\`));
            process.exit(1);
          }
        } catch (fallbackError: any) {
          console.error(chalk.red(\`\\n❌ Manual authentication failed: \${fallbackError.message}\\n\`));
          console.log(chalk.yellow("Configuration saved. You can run 'npm run setup' again to retry authentication.\\n"));
          process.exit(1);
        }
      }
    } catch (error: any) {
      testSpinner.fail(chalk.red("Authentication test failed"));
      console.error(chalk.red(\`Error: \${error.message}\\n\`));
      console.log(chalk.yellow("Configuration saved. Run 'npm run setup' again to retry authentication.\\n"));
      process.exit(1);
    }
  } else {
    console.log(chalk.green("\\n✅ Setup complete!\\n"));
  }

  // Step 9: Offer to save credentials globally (only if new credentials were entered)
  if (!useGlobalCreds && realm) {
    const { saveGlobally } = await prompts({
      type: "confirm",
      name: "saveGlobally",
      message: \`Save these credentials for all \${realm} services? (Other MCPs can reuse them)\`,
      initial: true,
    });

    if (saveGlobally) {
      const globalSaveSpinner = ora(\`Saving credentials globally for \${realm}\`).start();
      try {
        await saveGlobalCredentials(email, password, mfaScript || undefined);
        globalSaveSpinner.succeed(chalk.green(\`Credentials saved globally for \${realm}\`));
        console.log(chalk.dim(\`  Future MCPs for \${realm} will automatically find these credentials.\\n\`));
      } catch (error: any) {
        globalSaveSpinner.warn(chalk.yellow(\`Failed to save globally: \${error.message}\`));
        console.log(chalk.dim("  Local credentials are still saved and will work for this MCP.\\n"));
      }
    }
  }

  // Display next steps
  console.log(chalk.bold.blue("Next Steps:\\n"));
  console.log(chalk.dim("1. Add the MCP server to your Claude Desktop configuration:"));
  console.log(chalk.cyan(\`   "${toolName}-mcp": {\`));
  console.log(chalk.cyan('     "command": "node",'));
  console.log(chalk.cyan(\`     "args": ["\${process.cwd()}/dist/index.js"]\`));
  console.log(chalk.cyan("   }\\n"));
  console.log(chalk.dim("2. Restart Claude Desktop to load the MCP server"));
  console.log(chalk.dim("3. Test by asking Claude to interact with ${toolName}\\n"));
}

main().catch((error) => {
  console.error(chalk.red(\`\\n❌ Setup failed: \${error.message}\\n\`));
  process.exit(1);
});
`;
}

// ============================================================================
// Code Generation - Health Check CLI
// ============================================================================

export function generateHealthCheckModule(config: AzureAdSsoConfig): string {
  const { toolName } = config;

  return `#!/usr/bin/env node
/**
 * ${toolName} MCP Health Check
 *
 * Tests authentication and API connectivity.
 *
 * Generated by thesun.
 */

import chalk from "chalk";
import ora from "ora";
import { robustAuthenticate, validateSession } from "../robust-auth.js";
import { ConfigManager } from "../auth-config.js";
import { CredentialStore } from "../credential-store.js";

async function main() {
  console.log(chalk.bold.blue("\\n🏥 ${toolName} MCP Health Check\\n"));

  // Check 1: Configuration
  const configSpinner = ora("Checking configuration").start();
  const configManager = new ConfigManager();
  const config = configManager.load();

  if (!config) {
    configSpinner.fail(chalk.red("No configuration found"));
    console.log(chalk.yellow("\\nRun 'npm run setup' to configure the MCP.\\n"));
    process.exit(1);
  }
  configSpinner.succeed(chalk.green(\`Configuration found: \${config.instanceUrl}\`));

  // Check 2: Credentials
  const credSpinner = ora("Checking credentials").start();
  const credentialStore = new CredentialStore();
  const hasPassword = await credentialStore.hasPassword(config.email);

  if (!hasPassword) {
    credSpinner.fail(chalk.red("No password found in keychain"));
    console.log(chalk.yellow("\\nRun 'npm run setup' to reconfigure credentials.\\n"));
    process.exit(1);
  }
  credSpinner.succeed(chalk.green(\`Credentials found for: \${config.email}\`));

  // Check 3: Authentication
  const authSpinner = ora("Testing authentication").start();
  const authResult = await robustAuthenticate();

  if (!authResult.success) {
    authSpinner.fail(chalk.red(\`Authentication failed: \${authResult.error}\`));
    process.exit(1);
  }
  authSpinner.succeed(chalk.green(\`Authentication successful (method: \${authResult.method})\`));

  // Check 4: API Connectivity
  const apiSpinner = ora("Testing API connectivity").start();
  const isValid = await validateSession(config.instanceUrl, authResult.cookies!);

  if (!isValid) {
    apiSpinner.fail(chalk.red("API connectivity test failed"));
    process.exit(1);
  }
  apiSpinner.succeed(chalk.green("API connectivity confirmed"));

  console.log(chalk.green("\\n✅ All health checks passed!\\n"));
}

main().catch((error) => {
  console.error(chalk.red(\`\\n❌ Health check failed: \${error.message}\\n\`));
  process.exit(1);
});
`;
}

// ============================================================================
// Code Generation - Package.json additions
// ============================================================================

export function generatePackageJsonAdditions(): {
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
  scripts: Record<string, string>;
} {
  return {
    dependencies: {
      playwright: "^1.50.0",
      keytar: "^7.9.0",
      prompts: "^2.4.2",
      chalk: "^5.6.2",
      ora: "^8.2.0",
    },
    devDependencies: {
      "@types/prompts": "^2.4.9",
    },
    scripts: {
      setup: "tsx src/cli/setup.ts",
      "test-auth": "tsx src/cli/health-check.ts",
      postinstall: "playwright install firefox",
    },
  };
}

// ============================================================================
// Code Generation - README section
// ============================================================================

export function generateAzureAdSsoReadme(config: AzureAdSsoConfig): string {
  const { toolName } = config;

  return `## Authentication

This MCP uses **Azure AD SSO authentication** for enterprise environments.

### Quick Setup

\`\`\`bash
npm run setup
\`\`\`

This will prompt for:
- ${toolName} URL
- Your email address
- Your password (stored securely in system keychain)
- MFA/TOTP script path (optional)

The setup wizard will:
1. Store your credentials securely in the system keychain
2. Test your MFA script (if provided)
3. Perform a full authentication test
4. Save session cookies for immediate use

### How It Works

1. **Headless First**: Attempts fully automated background authentication
2. **Automatic Fallback**: Opens browser if headless fails (MFA, CAPTCHA, etc.)
3. **Cookie Caching**: Caches credentials for 8 hours
4. **401 Recovery**: Automatically re-authenticates on session expiration

### MFA/TOTP Setup (Optional)

If your organization requires MFA, create a script that outputs the TOTP code:

\`\`\`bash
#!/bin/bash
# ~/.config/totp-gen.sh
oathtool --totp -b "YOUR_TOTP_SECRET" 2>/dev/null
\`\`\`

Then provide the path during setup. The setup wizard will test your script to ensure it works.

### Manual Authentication

If automated auth fails:
1. A Firefox browser window will open
2. Complete the login manually
3. The MCP captures your session automatically

### Health Check

Test your configuration at any time:

\`\`\`bash
npm run test-auth
\`\`\`

### Security

- Passwords stored in OS keychain (macOS Keychain, Windows Credential Manager, Linux Secret Service)
- Cookies stored locally with 8-hour expiration
- Never transmitted except to ${toolName}

### Prerequisites

This MCP requires Firefox for browser automation. It will be installed automatically via:

\`\`\`bash
npm install  # Runs: playwright install firefox
\`\`\`

If you see browser-related errors, run manually:

\`\`\`bash
npx playwright install firefox
\`\`\`
`;
}

// ============================================================================
// Convenience Function - Generate All Files
// ============================================================================

export interface GeneratedAuthFiles {
  "src/azure-ad-automator.ts": string;
  "src/logger.ts": string;
  "src/credential-store.ts": string;
  "src/auth-config.ts": string;
  "src/robust-auth.ts": string;
  "src/utils/exec-file-no-throw.ts": string;
  "src/cli/setup.ts": string;
  "src/cli/health-check.ts": string;
}

export function generateAllAzureAdSsoFiles(
  config: AzureAdSsoConfig,
  hermesMode?: "auto" | "legacy",
): GeneratedAuthFiles {
  // In Hermes dual-mode, only robust-auth.ts changes (thin wrapper).
  // All other support files are still generated for legacy/standalone fallback.
  return {
    "src/azure-ad-automator.ts": generateAzureAdAutomatorModule(config),
    "src/logger.ts": generateLoggerModule(),
    "src/credential-store.ts": generateCredentialStoreModule(config),
    "src/auth-config.ts": generateConfigManagerModule(config),
    "src/robust-auth.ts": generateRobustAuthModule(config, hermesMode),
    "src/utils/exec-file-no-throw.ts": generateExecFileNoThrowModule(),
    "src/cli/setup.ts": generateSetupWizardModule(config),
    "src/cli/health-check.ts": generateHealthCheckModule(config),
  };
}

// ============================================================================
// Exports
// ============================================================================

export const AZURE_AD_SSO_AUTH = {
  generateAzureAdAutomatorModule,
  generateLoggerModule,
  generateExecFileNoThrowModule,
  generateCredentialStoreModule,
  generateConfigManagerModule,
  generateRobustAuthModule,
  generateSetupWizardModule,
  generateHealthCheckModule,
  generatePackageJsonAdditions,
  generateAzureAdSsoReadme,
  generateAllAzureAdSsoFiles,
};
