/**
 * Azure AD SSO Authentication Module for thesun
 *
 * Enterprise-grade browser-based SSO authentication for Microsoft/Azure AD protected services.
 * This module enables generated MCPs to authenticate to enterprise applications that use
 * Azure AD, Entra ID, or Microsoft SSO.
 *
 * Features:
 * - Headless-first authentication (background, no visible browser)
 * - Automatic fallback to visible browser if headless fails
 * - Automatic 401 detection and re-authentication
 * - Credential storage in system keychain (secure)
 * - Cookie caching with expiration detection
 * - MFA/TOTP script support (optional)
 * - Proper browser cleanup and timeouts
 *
 * Based on the battle-tested ServiceNow MCP authentication system.
 */

import { z } from "zod";

// ============================================================================
// Configuration Schema
// ============================================================================

export const AzureAdSsoConfigSchema = z.object({
  toolName: z
    .string()
    .describe("Name of the tool/service (e.g., 'servicenow')"),
  loginUrl: z.string().url().describe("URL that triggers Azure AD login"),
  successUrlPattern: z
    .string()
    .describe("Regex pattern for successful auth redirect"),
  headlessTimeout: z
    .number()
    .default(60000)
    .describe("Timeout for headless auth (ms)"),
  visibleTimeout: z
    .number()
    .default(300000)
    .describe("Timeout for visible browser auth (ms)"),
  cookieMaxAge: z
    .number()
    .default(8 * 60 * 60 * 1000)
    .describe("Cookie cache max age (ms)"),
  enableMfa: z
    .boolean()
    .default(false)
    .describe("Whether MFA/TOTP is expected"),
});

export type AzureAdSsoConfig = z.infer<typeof AzureAdSsoConfigSchema>;

// ============================================================================
// Code Generation - Robust Auth Module
// ============================================================================

/**
 * Generate the robust-auth.ts module for a new MCP
 */
export function generateRobustAuthModule(config: AzureAdSsoConfig): string {
  const {
    toolName,
    successUrlPattern,
    headlessTimeout,
    visibleTimeout,
    cookieMaxAge,
  } = config;

  return `/**
 * Robust Authentication Module for ${toolName} MCP
 *
 * Features:
 * - Automatic 401 detection and re-authentication
 * - Headless-first with automatic fallback to visible browser
 * - Proper timeouts to prevent hanging
 * - Browser process cleanup
 * - Credential auto-loading from config/keychain
 *
 * Generated by thesun with Azure AD SSO support.
 */

import { firefox, Browser, Page } from "playwright";
import { existsSync, readFileSync, writeFileSync, mkdirSync, unlinkSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { execFileSync } from "node:child_process";

const CONFIG_DIR = join(homedir(), ".${toolName}-mcp");
const COOKIE_FILE = join(CONFIG_DIR, "cookies.json");
const CONFIG_FILE = join(CONFIG_DIR, "config.json");

// Timeouts
const HEADLESS_AUTH_TIMEOUT = ${headlessTimeout};
const VISIBLE_AUTH_TIMEOUT = ${visibleTimeout};
const NAVIGATION_TIMEOUT = 30000;
const COOKIE_MAX_AGE = ${cookieMaxAge};

// Success URL pattern for detecting completed auth
const SUCCESS_URL_PATTERN = /${successUrlPattern.replace(/\//g, "\\/")}/;

export interface RobustAuthResult {
  success: boolean;
  cookies?: string;
  userToken?: string;
  instanceUrl?: string;
  error?: string;
  method?: "headless" | "visible" | "cached";
}

interface StoredConfig {
  email: string;
  instanceUrl: string;
  mfaScript?: string;
  headless?: boolean;
}

// ============================================================================
// Credential Management
// ============================================================================

function loadConfig(): StoredConfig | null {
  if (!existsSync(CONFIG_FILE)) {
    return null;
  }
  try {
    return JSON.parse(readFileSync(CONFIG_FILE, "utf-8"));
  } catch {
    return null;
  }
}

async function getPasswordFromKeychain(email: string): Promise<string | null> {
  try {
    const keytar = await import("keytar").catch(() => null);
    if (keytar) {
      return await keytar.default.getPassword("${toolName}-mcp", email);
    }

    // Fallback to macOS security command
    if (process.platform === "darwin") {
      try {
        const result = execFileSync("security", [
          "find-generic-password",
          "-a", email,
          "-s", "${toolName}-mcp",
          "-w"
        ], { encoding: "utf-8" }).trim();
        return result || null;
      } catch {
        return null;
      }
    }

    return null;
  } catch {
    return null;
  }
}

async function loadCredentials(): Promise<{
  email: string;
  password: string;
  mfaScript: string;
  instanceUrl: string;
  headless: boolean;
} | null> {
  const config = loadConfig();
  if (!config) {
    return null;
  }

  const password = await getPasswordFromKeychain(config.email);
  if (!password) {
    return null;
  }

  return {
    email: config.email,
    password: password,
    mfaScript: config.mfaScript || "",
    instanceUrl: config.instanceUrl,
    headless: config.headless ?? true,
  };
}

// ============================================================================
// Cookie Management
// ============================================================================

function loadCachedCookies(): RobustAuthResult | null {
  if (!existsSync(COOKIE_FILE)) {
    return null;
  }

  try {
    const data = JSON.parse(readFileSync(COOKIE_FILE, "utf-8"));
    const timestamp = new Date(data.timestamp);
    const age = Date.now() - timestamp.getTime();

    if (age > COOKIE_MAX_AGE) {
      console.error("⚠️  Cached cookies expired");
      return null;
    }

    const cookieString = data.cookies
      .map((c: any) => \`\${c.name}=\${c.value}\`)
      .join("; ");

    return {
      success: true,
      cookies: cookieString,
      userToken: data.userToken || "",
      instanceUrl: data.instanceUrl,
      method: "cached",
    };
  } catch {
    return null;
  }
}

function saveCookies(instanceUrl: string, cookies: any[], userToken?: string): void {
  if (!existsSync(CONFIG_DIR)) {
    mkdirSync(CONFIG_DIR, { recursive: true });
  }

  const data = {
    instanceUrl,
    cookies,
    userToken: userToken || "",
    timestamp: new Date().toISOString(),
    source: "robust-auth",
  };

  writeFileSync(COOKIE_FILE, JSON.stringify(data, null, 2));
  console.error(\`✅ Cookies saved (\${cookies.length} cookies)\`);
}

function clearCookies(): void {
  if (existsSync(COOKIE_FILE)) {
    try {
      unlinkSync(COOKIE_FILE);
    } catch {
      // Ignore errors
    }
  }
}

// ============================================================================
// Azure AD Automation
// ============================================================================

async function performAzureAdLogin(
  page: Page,
  credentials: { email: string; password: string; mfaScript: string },
  timeout: number
): Promise<{ success: boolean; cookies?: any[]; error?: string }> {
  const startTime = Date.now();

  try {
    // Wait for and fill email field
    console.error("Detecting email field...");
    const emailField = await page.waitForSelector(
      'input[type="email"], input[name="loginfmt"], input[name="login"], input[name="email"]',
      { timeout: 30000 }
    );

    await emailField.fill(credentials.email);
    console.error("Email field filled");

    // Click next/submit for email
    const nextButton = await page.waitForSelector(
      'input[type="submit"], button[type="submit"], #idSIButton9',
      { timeout: 10000 }
    );
    await nextButton.click();
    console.error("Email submitted");

    // Wait for password field
    await page.waitForTimeout(1500);
    console.error("Detecting password field...");
    const passwordField = await page.waitForSelector(
      'input[type="password"], input[name="passwd"], input[name="password"]',
      { timeout: 30000 }
    );

    await passwordField.fill(credentials.password);
    console.error("Password field filled");

    // Click sign in
    const signInButton = await page.waitForSelector(
      'input[type="submit"], button[type="submit"], #idSIButton9',
      { timeout: 10000 }
    );
    await signInButton.click();
    console.error("Sign in clicked");

    // Handle MFA if present
    await page.waitForTimeout(1000);
    const mfaField = await page.waitForSelector(
      'input[name="otc"], input[name="totp"], input[aria-label*="code"], #idTxtBx_SAOTCC_OTC',
      { timeout: 20000 }
    ).catch(() => null);

    if (mfaField && credentials.mfaScript) {
      console.error("MFA field detected, executing script...");
      try {
        // Execute MFA script safely using execFileSync
        const mfaCode = execFileSync(credentials.mfaScript, [], { encoding: "utf-8" }).trim();
        await mfaField.fill(mfaCode);

        const verifyButton = await page.waitForSelector(
          'input[type="submit"], button[type="submit"], #idSubmit_SAOTCC_Continue',
          { timeout: 5000 }
        );
        await verifyButton.click();
        console.error("MFA code submitted");
      } catch (error: any) {
        console.error("MFA script failed:", error.message);
      }
    } else if (mfaField && !credentials.mfaScript) {
      console.error("MFA field detected but no script configured - waiting for manual entry...");
    }

    // Handle "Stay signed in?" prompt
    await page.waitForTimeout(1000);
    const staySignedIn = await page.waitForSelector(
      '#idBtn_Back, #idSIButton9, button:has-text("Yes"), button:has-text("No")',
      { timeout: 10000 }
    ).catch(() => null);

    if (staySignedIn) {
      const yesButton = await page.$('#idSIButton9, button:has-text("Yes")');
      if (yesButton) {
        await yesButton.click();
        console.error("'Stay signed in?' accepted");
      }
    }

    // Wait for redirect to success URL
    console.error("Waiting for redirect...");
    await page.waitForURL(SUCCESS_URL_PATTERN, { timeout: timeout - (Date.now() - startTime) });
    console.error("Redirected to target service");

    // Get cookies
    const context = page.context();
    const cookies = await context.cookies();

    return { success: true, cookies };
  } catch (error: any) {
    return { success: false, error: error.message };
  }
}

// ============================================================================
// Main Authentication Functions
// ============================================================================

async function performAuth(
  instanceUrl: string,
  credentials: { email: string; password: string; mfaScript: string },
  headless: boolean,
  timeout: number
): Promise<RobustAuthResult> {
  let browser: Browser | null = null;

  try {
    console.error(\`Starting \${headless ? "headless" : "visible"} authentication...\`);

    browser = await firefox.launch({
      headless,
      timeout: 30000,
    });

    const context = await browser.newContext({
      viewport: { width: 1280, height: 800 },
    });

    const page = await context.newPage();

    await page.goto(instanceUrl, {
      waitUntil: "networkidle",
      timeout: NAVIGATION_TIMEOUT,
    });

    const authPromise = performAzureAdLogin(page, credentials, timeout);
    const timeoutPromise = new Promise<never>((_, reject) => {
      setTimeout(() => reject(new Error("Authentication timeout")), timeout);
    });

    const result = await Promise.race([authPromise, timeoutPromise]);

    if (result.success && result.cookies) {
      let userToken = "";
      try {
        userToken = await page.evaluate(() => {
          return (window as any).g_ck || (window as any).NOW?.g_ck || "";
        });
      } catch {
        // Ignore
      }

      saveCookies(instanceUrl, result.cookies, userToken);

      const cookieString = result.cookies
        .map((c: any) => \`\${c.name}=\${c.value}\`)
        .join("; ");

      return {
        success: true,
        cookies: cookieString,
        userToken,
        instanceUrl,
        method: headless ? "headless" : "visible",
      };
    }

    return { success: false, error: result.error || "Authentication failed" };
  } catch (error: any) {
    return { success: false, error: error.message };
  } finally {
    if (browser) {
      try {
        await browser.close();
      } catch {
        // Ignore
      }
    }
  }
}

export async function robustAuthenticate(instanceUrl?: string): Promise<RobustAuthResult> {
  const creds = await loadCredentials();
  if (!creds) {
    return {
      success: false,
      error: "No credentials configured. Run 'npm run setup' first.",
    };
  }

  const targetUrl = instanceUrl || creds.instanceUrl;
  console.error(\`🔐 Authenticating to \${targetUrl}\`);

  const cached = loadCachedCookies();
  if (cached && cached.success) {
    console.error("✅ Using cached cookies");
    return cached;
  }

  console.error("🔄 Attempting headless authentication...");
  const headlessResult = await performAuth(targetUrl, creds, true, HEADLESS_AUTH_TIMEOUT);

  if (headlessResult.success) {
    console.error("✅ Headless authentication successful!");
    return headlessResult;
  }

  console.error(\`⚠️  Headless auth failed: \${headlessResult.error}\`);
  console.error("🌐 Opening visible browser for manual authentication...");

  const visibleResult = await performAuth(targetUrl, creds, false, VISIBLE_AUTH_TIMEOUT);

  if (visibleResult.success) {
    console.error("✅ Visible browser authentication successful!");
    return visibleResult;
  }

  return {
    success: false,
    error: \`Authentication failed. Headless: \${headlessResult.error}. Visible: \${visibleResult.error}\`,
  };
}

export async function handleAuthFailure(): Promise<RobustAuthResult> {
  console.error("\\n⚠️  401 Unauthorized - Re-authenticating...\\n");
  clearCookies();
  return robustAuthenticate();
}

export async function validateSession(instanceUrl: string, cookies: string): Promise<boolean> {
  try {
    const response = await fetch(\`\${instanceUrl}/api/now/table/sys_user?sysparm_limit=1\`, {
      headers: {
        Cookie: cookies,
        Accept: "application/json",
      },
    });
    return response.status === 200;
  } catch {
    return false;
  }
}

export async function getAuthHeaders(): Promise<Record<string, string>> {
  const result = await robustAuthenticate();

  if (!result.success) {
    throw new Error(result.error || "Authentication failed");
  }

  const headers: Record<string, string> = {};

  if (result.cookies) {
    headers["Cookie"] = result.cookies;
  }

  if (result.userToken) {
    headers["x-usertoken"] = result.userToken;
  }

  return headers;
}
`;
}

// ============================================================================
// Code Generation - Setup Wizard
// ============================================================================

/**
 * Generate the setup wizard (CLI script)
 */
export function generateSetupWizardModule(config: AzureAdSsoConfig): string {
  const { toolName } = config;
  const envPrefix = toolName.toUpperCase().replace(/-/g, "_");

  return `#!/usr/bin/env node
/**
 * ${toolName} MCP Setup Wizard
 *
 * Interactive setup for Azure AD SSO authentication.
 * Stores credentials securely in system keychain.
 *
 * Generated by thesun.
 */

import prompts from "prompts";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const CONFIG_DIR = join(homedir(), ".${toolName}-mcp");
const CONFIG_FILE = join(CONFIG_DIR, "config.json");

async function getKeytar() {
  try {
    const keytar = await import("keytar");
    return keytar.default;
  } catch {
    console.error("⚠️  keytar not available - passwords will not be stored securely");
    return null;
  }
}

async function main() {
  console.log("\\n🔧 ${toolName} MCP Setup Wizard\\n");
  console.log("This will configure Azure AD SSO authentication.\\n");

  const { instanceUrl } = await prompts({
    type: "text",
    name: "instanceUrl",
    message: "${toolName} URL:",
    initial: process.env.${envPrefix}_URL || "",
    validate: (v) => v.startsWith("https://") || "Must be an HTTPS URL",
  });

  if (!instanceUrl) {
    console.log("Setup cancelled.");
    process.exit(1);
  }

  const { email } = await prompts({
    type: "text",
    name: "email",
    message: "Your email address:",
    validate: (v) => v.includes("@") || "Invalid email",
  });

  if (!email) {
    console.log("Setup cancelled.");
    process.exit(1);
  }

  const { password } = await prompts({
    type: "password",
    name: "password",
    message: "Your password:",
    validate: (v) => v.length > 0 || "Password required",
  });

  if (!password) {
    console.log("Setup cancelled.");
    process.exit(1);
  }

  const { mfaScript } = await prompts({
    type: "text",
    name: "mfaScript",
    message: "Path to MFA/TOTP script (leave empty to skip):",
    initial: "",
    validate: (v) => {
      if (!v) return true;
      if (!existsSync(v)) return \`File not found: \${v}\`;
      return true;
    },
  });

  if (!existsSync(CONFIG_DIR)) {
    mkdirSync(CONFIG_DIR, { recursive: true });
  }

  const config = {
    instanceUrl: instanceUrl.replace(/\\/$/, ""),
    email,
    mfaScript: mfaScript || "",
    headless: true,
  };

  writeFileSync(CONFIG_FILE, JSON.stringify(config, null, 2));
  console.log(\`\\n✅ Config saved to \${CONFIG_FILE}\`);

  const keytar = await getKeytar();
  if (keytar) {
    await keytar.setPassword("${toolName}-mcp", email, password);
    console.log("✅ Password stored securely in system keychain");
  } else {
    console.log("⚠️  Password NOT stored - keytar not available");
  }

  console.log("\\n🎉 Setup complete!\\n");
}

main().catch(console.error);
`;
}

// ============================================================================
// Code Generation - Package.json additions
// ============================================================================

export function generatePackageJsonAdditions(): {
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
  scripts: Record<string, string>;
} {
  return {
    dependencies: {
      playwright: "^1.50.0",
      keytar: "^7.9.0",
      prompts: "^2.4.2",
    },
    devDependencies: {
      "@types/prompts": "^2.4.9",
    },
    scripts: {
      setup: "tsx src/cli/setup.ts",
      postinstall: "playwright install firefox",
    },
  };
}

// ============================================================================
// Code Generation - README section
// ============================================================================

export function generateAzureAdSsoReadme(config: AzureAdSsoConfig): string {
  const { toolName } = config;

  return `## Authentication

This MCP uses **Azure AD SSO authentication** for enterprise environments.

### Quick Setup

\`\`\`bash
npm run setup
\`\`\`

This will prompt for:
- ${toolName} URL
- Your email address
- Your password (stored securely in system keychain)
- MFA/TOTP script path (optional)

### How It Works

1. **Headless First**: Attempts fully automated background authentication
2. **Automatic Fallback**: Opens browser if headless fails (MFA, CAPTCHA, etc.)
3. **Cookie Caching**: Caches credentials for 8 hours
4. **401 Recovery**: Automatically re-authenticates on session expiration

### MFA/TOTP Setup (Optional)

If your organization requires MFA, create a script that outputs the TOTP code:

\`\`\`bash
#!/bin/bash
# ~/.config/totp-gen.sh
oathtool --totp -b "YOUR_TOTP_SECRET" 2>/dev/null
\`\`\`

Then provide the path during setup.

### Manual Authentication

If automated auth fails:
1. A Firefox browser window will open
2. Complete the login manually
3. The MCP captures your session automatically

### Security

- Passwords stored in OS keychain (macOS Keychain, Windows Credential Manager, Linux Secret Service)
- Cookies stored locally with 8-hour expiration
- Never transmitted except to ${toolName}
`;
}

// ============================================================================
// Exports
// ============================================================================

export const AZURE_AD_SSO_AUTH = {
  generateRobustAuthModule,
  generateSetupWizardModule,
  generatePackageJsonAdditions,
  generateAzureAdSsoReadme,
};
